version: '3'
services:
    web:
      image: shimine/cua-arbiter-alpine
      ports:
        - "8000:8000"
      depends_on:
        - db
      command: python ./manage.py makemigrations arbiter&& python ./manage.py migrate && python ./manage.py shell < initadmin.py

    db: 
      image: postgres
      ports:
        - "5432:5432"
      environment: 
        - POSTGRES_PASSWORD=123456
        - POSTGRES_DB=arbiter_dj
        - POSTGRES_USER=luna
        - POSTGRES_PASSWORD=luna

    redis: 
      image: redis

    elk:
      image: shimine/cua-arbiter-elk
      ports:
        - "5601:5601"
        - "9200:9200"
        - "5044:5044"
