version: '3'
services:
    web:
      image: shimine/cua-arbiter:1.3-alpine
      links:
        - db
        - redis
      ports:
        - "8000:8000"
      depends_on:
        - db
      command: python ./manage.py makemigrations arbiter&& python ./manage.py migrate
    db: 
      image: mysql
      ports:
        - "3306:3306"
      environment: 
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=arbiter_dj
        - MYSQL_USER=luna 
        - MYSQL_PASSWORD=luna
    redis: 
      image: redis
      ports:
        - "6379:6379"
    elk:
      image: sebp/elk
      ports:
        - "5601:5601"
        - "9200:9200"
        - "5044:5044"